export const FETCH_PENDING = "FETCH_PENDING";
export const FETCH_ERROR = "FECH_ERROR";

export const FETCH_BRAND_SUCCESS = "FETCH_BRAND_SUCCESS";
export const FETCH_MODEL_SUCCESS = "FETCH_MODEL_SUCCESS";
export const FETCH_YEAR_SUCCESS = "FETCH_YEAR_SUCCESS";
export const FETCH_RESULT_SUCCESS = "FETCH_RESULT_SUCCESS";

export const CHANGE_STEP = "CHANGE_STEP";
export const RESET_ALL = "RESET_ALL";
export const SET_VEHICLE = "SET_VEHICLE";
export const SET_BRAND = "SET_BRAND";
export const SET_MODEL = "SET_MODEL";
export const SET_YEAR = "SET_YEAR";
export const SET_RESULT = "SET_RESULT";
